openapi: 3.0.3
info:
  title: Grocery Tracker API
  description: Definition of available methods to interact with the Grocery Tracker application back-end.
  version: 1.0.0-SNAPSHOT
servers:
  - url: 'http://grocery-tracker-back-8.eu-central-1.elasticbeanstalk.com/'
    description: Production environment
tags:
  - name: Purchase locations
    description: Operations related to purchase locations
  - name: Purchases
    description: Operations related to grocery purchases
paths:
  /purchaseLocations:
    get:
      operationId: getPurchaseLocations
      summary: Get existing purchase locations, that is, locations where at least one purchase has already been done.
      description: Retrieve a list of the locations in which grocery purchases have been previsously registered.
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseLocation'
          description: List of existing purchase locations
      tags:
        - Purchase locations
  /purchases:
    post:
      operationId: registerPurchase
      summary: Registers a purchase.
      description: Registers a purchase, along with information such as descriptions tags, sales unit and price.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
        required: true
      responses:
        201:
          description: Grocery line has been properly registered
      tags:
        - Purchases
components:
  schemas:
    Packaging:
      type: object
      properties:
        nbUnitPerPackage:
          type: integer
          default: 1
        unitMeasurements:
          $ref: '#/components/schemas/UnitMeasurement'
    UnitMeasurement:
      type: object
      properties:
        type:
          type: string
          enum: [ml, cl, l, g, kg]
        quantity:
          type: number
      required:
        - type
        - quantity
    PurchaseLocation:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        locationTag:
          type: string
      required:
        - description
        - locationTag
    PurchaseRequest:
      description: Request object representing the purchase to be registered in the application
      type: object
      properties:
        date:
          type: string
          pattern: 'dddd-dd-dd'
        location:
          $ref: '#/components/schemas/PurchaseLocation'
        brand:
          type: string
        descriptionTags:
          type: array
          items:
            type: string
          minimum: 1
        unitPrice:
          type: number
        packaging:
          $ref: '#/components/schemas/Packaging'
      required:
        - date
        - location
        - descriptionTags
        - unitPrice

