openapi: 3.0.3
info:
  title: Grocery Tracker API
  description: Definition of available methods to interact with the Grocery Tracker application back-end.
  version: 1.0.0-SNAPSHOT
servers:
  - url: 'http://grocery-tracker-back-8.eu-central-1.elasticbeanstalk.com/'
    description: Production environment
tags:
  - name: Purchases
    description: Operations related to set of purchases
  - name: Purchase
    description: Operations related to single purchase
paths:
  /purchases:
    post:
      tags:
        - Purchases
      operationId: registerPurchase
      summary: Registers a purchase.
      description: Registers a purchase, along with purchased items and the shop in which the purchase has been made.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
        required: true
      responses:
        201:
          description: Purchase has been properly registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseResponse'
components:
  schemas:
    Packaging:
      type: object
      properties:
        nbUnitPerPackage:
          type: integer
          default: 1
        unitMeasurements:
          $ref: '#/components/schemas/UnitMeasurement'

    UnitMeasurement:
      type: object
      properties:
        type:
          type: string
          enum: [ pc, ml, cl, l, g, kg ]
          default: pc
        quantity:
          type: integer
          default: 1

    Shop:
      description: Shop in which a purchase has been made
      type: object
      properties:
        name:
          type: string
        location:
          type: string
      required:
        - name
        - location

    PurchaseItem:
      description: Item that has been purchased as part of a purchase
      type: object
      properties:
        brand:
          type: string
        productTags:
          type: array
          items:
            type: string
            minItems: 1
        unitPrice:
          type: number
        nbUnit:
          type: integer
          minimum: 1
        packaging:
          $ref: '#/components/schemas/Packaging'
      required:
        - brand
        - productTags
        - unitPrice
        - nbUnit
        - packaging

    PurchaseRequest:
      description: Request object representing the purchase to be registered in the application
      type: object
      properties:
        date:
          type: string
          format: date
        shop:
          $ref: '#/components/schemas/Shop'
        amount:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/PurchaseItem'
          minItems: 1
      required:
        - date
        - shop
        - amount
        - items

    PurchaseResponse:
      description: Representation of a purchase that has been persisted in the system.
      allOf:
        - $ref: '#/components/schemas/PurchaseRequest'
        - type: object
          properties:
            id:
              type: integer
          required:
            - id