openapi: 3.0.3
info:
  title: Persistence data model
  description: Definitions of data structures that are persisted to and read from the DynamoDB database
  version: 1.0.0-SNAPSHOT
paths: { }
components:
  schemas:
    ExpenseEntity:
      type: object
      properties:
        ownr:
          type: string
        timestamp:
          type: string
        date:
          type: string
          format: date
        amount:
          type: number
        tags:
          type: array
          items:
            type: string
          minItems: 1
        description:
          type: string
        creditCard:
          type: boolean
        creditCardPaid:
          type: boolean
      required:
        - ownr
        - timestamp
        - date
        - amount
        - tags
